name: msds2025a-ml2
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.6.2
  - numpy=1.23.5
  - pandas=1.5.2
  - python=3.9.13
  - ipykernel=6.19.4
  - scikit-learn=1.2.0
  - seaborn=0.12.2
  - pip=22.3.1
  - scipy=1.10.0
  - notebook=6.5.2
  - shap=0.41.0
  - lime=0.2.0.1
  - eli5=0.13.0
  - imbalanced-learn=0.10.1
  - statsmodels=0.13.5
  - pip:
    - jupyter-contrib-nbextensions==0.7.0
    - ipywidgets==8.0.4
    - torch==1.13.1
    - prophet==1.1.1